//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMA.Logics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.ApplicationDependencies = new HashSet<ApplicationDependencies>();
            this.ApplicationSite = new HashSet<ApplicationSite>();
            this.LanguageCode = new HashSet<LanguageCode>();
        }
    
        public int Id { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Owner { get; set; }
        public string SecurityModelUrl { get; set; }
        public string CartaUrl { get; set; }
        public string RiskAssessmentUrl { get; set; }
        public string SplunkUrl { get; set; }
        public Nullable<int> Core { get; set; }
        public Nullable<int> AppTier { get; set; }
        public Nullable<int> UserCount { get; set; }
        public Nullable<int> LicenseType { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdVendor { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDependencies> ApplicationDependencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationSite> ApplicationSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageCode> LanguageCode { get; set; }
    }
}
