//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMA.Logics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDependencies
    {
        public int Id { get; set; }
        public int IdApplication { get; set; }
        public int IdDependencies { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Dependencies Dependencies { get; set; }
    }
}
