//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMA.Logics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMADBEntities : DbContext
    {
        public EMADBEntities()
            : base("name=EMADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationDependencies> ApplicationDependencies { get; set; }
        public virtual DbSet<ApplicationSite> ApplicationSite { get; set; }
        public virtual DbSet<Database> Database { get; set; }
        public virtual DbSet<Dependencies> Dependencies { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LanguageCode> LanguageCode { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<SiteGroup> SiteGroup { get; set; }
        public virtual DbSet<SiteServer> SiteServer { get; set; }
        public virtual DbSet<Statics> Statics { get; set; }
        public virtual DbSet<TerminalServer> TerminalServer { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<VendorContacts> VendorContacts { get; set; }
    }
}
